'use client'

import Link from 'next/link'
import { usePathname } from 'next/navigation'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import CaseStudyMiniNav from '@/components/case-studies/CaseStudyMiniNav'
import CaseStudyNext from '@/components/case-studies/CaseStudyNext'
import { getLocaleFromPath, localizePath, type Locale } from '@/lib/i18n'

const liveUrl = 'https://search-signal.vercel.app'
const githubUrl = 'https://github.com/RaulMermans/SearchSignal'

type Copy = {
  back: string
  eyebrow: string
  subtitle: string
  description: string
  status: string
  live: string
  github: string
  linksLabel: string
  nav: Array<[string, string]>
  metadata: Array<[string, string]>
  premise: { eyebrow: string; title: string; body: string }
  problem: { eyebrow: string; title: string; body: string; cards: Array<[string, string]> }
  insight: { eyebrow: string; title: string; body: string; question: string }
  system: { eyebrow: string; title: string; body: string; steps: Array<[string, string]> }
  experience: { eyebrow: string; title: string; body: string; surfaces: Array<[string, string]> }
  explainability: { eyebrow: string; title: string; body: string; points: string[] }
  decisions: { eyebrow: string; title: string; items: Array<[string, string]> }
  architecture: { eyebrow: string; title: string; body: string; packages: Array<[string, string]> }
  trust: { eyebrow: string; title: string; implementedLabel: string; futureLabel: string; implemented: string[]; future: string[] }
  quality: { eyebrow: string; title: string; body: string; checks: Array<[string, string]> }
  outcome: { eyebrow: string; title: string; body: string; points: string[] }
  next: { eyebrow: string; title: string; items: string[] }
  final: { title: string; description: string; live: string; github: string; back: string }
}

const copy: Record<Locale, Copy> = {
  en: {
    back: 'Case studies',
    eyebrow: 'Ecommerce search / Product systems',
    subtitle: 'Search quality starts before search.',
    description: 'SearchSignal is an inspectable catalog-readiness framework for finding the product-data issues that shape ecommerce search before a customer enters a query.',
    status: 'Deployed synthetic demonstrator',
    live: 'Open live demonstrator',
    github: 'View GitHub repository',
    linksLabel: 'Project links',
    nav: [['Premise', '#premise'], ['System', '#system'], ['Experience', '#experience'], ['Decisions', '#decisions'], ['Architecture', '#architecture'], ['Boundaries', '#boundaries'], ['Outcome', '#outcome']],
    metadata: [['Discipline', 'Product strategy, UX, systems design, development'], ['Industry', 'Ecommerce, search and discovery'], ['Year', '2026'], ['Role', 'Strategy, information architecture, UX, implementation']],
    premise: { eyebrow: '01 / Premise', title: 'Search interfaces inherit the quality of the information beneath them.', body: 'Ranking, filters, synonyms, and semantic retrieval all depend on a catalog that can be understood consistently. When a record carries conflicting identifiers, unclear availability, malformed prices, or thin descriptions, the issue travels downstream. It appears later as irrelevant results, broken filters, products that disappear from search, and debugging with no clear starting point.' },
    problem: { eyebrow: '02 / Problem', title: 'Ecommerce search often fails upstream.', body: 'Catalog data evolves under commercial pressure and usually arrives from more than one source. A migration or new retrieval model can expose inconsistencies that were already present. SearchSignal makes those conditions inspectable before they become a customer-facing problem.', cards: [['Identifiers drift', 'A product cannot be joined, deduplicated, or traced reliably when its identifiers conflict.'], ['Product facts blur', 'Price, availability, and attributes lose meaning when their format or source is ambiguous.'], ['Retrieval amplifies gaps', 'Semantic methods can make sparse or poorly structured source information more influential, not more complete.']] },
    insight: { eyebrow: '03 / Strategic insight', title: 'Search eligibility is a product decision.', body: 'SearchSignal changes the order of operations. It assesses whether a product has enough valid, interpretable information to support a search experience before that record enters an index. A source record can exist in a catalog and still be a poor candidate for retrieval.', question: 'Should this product be searchable at all?' },
    system: { eyebrow: '04 / System', title: 'A visible path from source record to search result.', body: 'Each stage emits evidence that connects source quality, indexing decisions, and retrieval outcomes. The framework does not treat search as an isolated interface concern.', steps: [['Source catalog', 'Fictional product records retain their source structure and constraints.'], ['Map', 'Fields move into a canonical product contract.'], ['Validate', 'Required evidence and structural correctness are checked.'], ['Normalize', 'Named rules standardize interpretable values.'], ['Assess', 'Readiness is evaluated against the information available.'], ['Eligibility', 'Admission or rejection remains tied to visible evidence.'], ['Retrieve', 'Eligible products can be explored through three deterministic modes.'], ['Evaluate', 'Golden queries make retrieval behavior comparable over time.']] },
    experience: { eyebrow: '05 / Product experience', title: 'Three surfaces, one argument.', body: 'The public experience turns a technical workflow into a readable product story without claiming that the demonstrator is production infrastructure.', surfaces: [['Landing', 'Explains the framework and the synthetic demonstration boundary.'], ['Search demo', 'Explores fictional products with keyword, deterministic semantic, and hybrid retrieval.'], ['Readiness console', 'Shows catalog scenarios, validation findings, normalization, readiness, eligibility, and indexing admission.']] },
    explainability: { eyebrow: '06 / Designing for explainability', title: 'A decision is more useful when its evidence is visible.', body: 'SearchSignal avoids hidden corrections and opaque automation. A change, block, or admission should be understandable to the person responsible for the catalog.', points: ['Named normalization rules show how a value changed.', 'Eligibility decisions retain the evidence behind the status.', 'Deterministic behavior makes the same input reproducible.', 'Provider and configuration failures stay controlled and legible.'] },
    decisions: { eyebrow: '07 / Product decisions', title: 'The constraints are part of the product.', items: [['Deterministic by default', 'Critical catalog and eligibility behavior is reproducible. The tradeoff is a narrower system, with a clearer trail to inspect and test.'], ['Normalize explicitly', 'The framework standardizes values only through named rules. It does not silently invent product facts.'], ['Separate demo from production', 'Synthetic fixtures and deterministic providers never masquerade as live merchant infrastructure.'], ['Fail closed', 'Missing production-provider configuration returns a controlled failure. It does not fall back to demo behavior.'], ['Make evidence visible', 'Readiness and retrieval decisions can be examined instead of trusted blindly.'], ['Keep boundaries honest', 'Future connectors, providers, persistence, and operations are documented as future work.']] },
    architecture: { eyebrow: '08 / Architecture', title: 'Clear responsibilities make the system easier to reason about.', body: 'SearchSignal is a TypeScript pnpm monorepo. Next.js and React provide the public surface. Zod defines shared structures. Vitest exercises behaviour. Vercel is the deployment target. The architecture separates product concerns so one part can change without obscuring another.', packages: [['Source mapping', 'Translates source records into a canonical structure.'], ['Validation and normalization', 'Checks required evidence and applies explicit data rules.'], ['Readiness and eligibility', 'Assesses whether a record can support search.'], ['Retrieval and evaluation', 'Runs deterministic modes and compares them with golden queries.'], ['Public interface', 'Explains the workflow through the landing page, demo, and console.']] },
    trust: { eyebrow: '09 / Building trust through constraints', title: 'The demonstrator is specific about what exists.', implementedLabel: 'Implemented', futureLabel: 'Future', implemented: ['Synthetic ecommerce catalog', 'Deterministic keyword, semantic, and hybrid retrieval', 'Catalog validation and normalization', 'Readiness assessment and eligibility', 'Golden-query evaluation', 'Public UI and automated verification'], future: ['Live Typesense integration', 'Live embedding provider', 'Shopify connector', 'Durable merchant persistence', 'Search analytics and background synchronization', 'Multi-tenant SaaS infrastructure'] },
    quality: { eyebrow: '10 / Quality and verification', title: 'Evidence extends to the build.', body: 'The recorded clean Node 22 verification run passed frozen installation, linting, type checking, all tests, production build, and the Vercel-readiness validator. It also covers route smoke, responsive and keyboard checks, plus controlled failure behavior. The remaining 200% zoom capture evidence is documented as open rather than represented as complete.', checks: [['340', 'automated tests passed'], ['20', 'Vercel readiness checks passed'], ['3', 'public product surfaces'], ['0', 'live merchant-data claims']] },
    outcome: { eyebrow: '11 / Outcome', title: 'A way to reason about search before ranking.', body: 'SearchSignal is a working product demonstrator for a question that is often left implicit: is this catalog information ready to support search?', points: ['An inspectable catalog-readiness workflow', 'A system for explaining search eligibility', 'A controlled environment for comparing retrieval approaches', 'A technical proof of concept with documented production boundaries'] },
    next: { eyebrow: '12 / What comes next', title: 'Logical validation steps, not a generic roadmap.', items: ['Connect a live search provider.', 'Persist catalog evidence over time.', 'Add Shopify ingestion.', 'Introduce privacy-aware search analytics.', 'Run background synchronization.', 'Test the workflow with a merchant pilot.'] },
    final: { title: 'Better search begins with better information.', description: 'SearchSignal treats search quality as a systems problem before it becomes a ranking problem.', live: 'Open live demonstrator', github: 'View GitHub repository', back: 'Back to case studies' },
  },
  es: {
    back: 'Casos de estudio',
    eyebrow: 'Búsqueda ecommerce / Sistemas de producto',
    subtitle: 'La calidad de búsqueda empieza antes de buscar.',
    description: 'SearchSignal es un framework inspeccionable de preparación de catálogo que detecta los problemas de datos que condicionan la búsqueda ecommerce antes de que una persona escriba una consulta.',
    status: 'Demostrador sintético desplegado',
    live: 'Abrir demostrador',
    github: 'Ver repositorio en GitHub',
    linksLabel: 'Enlaces del proyecto',
    nav: [['Premisa', '#premise'], ['Sistema', '#system'], ['Experiencia', '#experience'], ['Decisiones', '#decisions'], ['Arquitectura', '#architecture'], ['Límites', '#boundaries'], ['Resultado', '#outcome']],
    metadata: [['Disciplina', 'Estrategia de producto, UX, diseño de sistemas, desarrollo'], ['Industria', 'Ecommerce, búsqueda y descubrimiento'], ['Año', '2026'], ['Rol', 'Estrategia, arquitectura de información, UX, implementación']],
    premise: { eyebrow: '01 / Premisa', title: 'Las interfaces de búsqueda heredan la calidad de la información que tienen debajo.', body: 'Ranking, filtros, sinónimos y recuperación semántica dependen de un catálogo que se pueda interpretar con consistencia. Si un registro tiene identificadores en conflicto, disponibilidad poco clara, precios mal formados o descripciones mínimas, el problema viaja hacia abajo. Después aparece como resultados irrelevantes, filtros rotos, productos que desaparecen y depuración sin un punto de partida claro.' },
    problem: { eyebrow: '02 / Problema', title: 'La búsqueda ecommerce suele fallar antes de llegar a la búsqueda.', body: 'Los datos de catálogo cambian bajo presión comercial y suelen llegar desde más de una fuente. Una migración o un nuevo modelo de recuperación puede exponer inconsistencias que ya estaban presentes. SearchSignal permite inspeccionarlas antes de que afecten a una experiencia de cliente.', cards: [['Los identificadores divergen', 'Un producto no se puede vincular, deduplicar o rastrear de forma fiable cuando sus identificadores entran en conflicto.'], ['Los hechos se vuelven ambiguos', 'Precio, disponibilidad y atributos pierden significado cuando su formato u origen no está claro.'], ['La recuperación amplifica vacíos', 'Los métodos semánticos pueden hacer más influyente una información fuente escasa o mal estructurada, no más completa.']] },
    insight: { eyebrow: '03 / Insight estratégico', title: 'La elegibilidad para búsqueda es una decisión de producto.', body: 'SearchSignal cambia el orden de trabajo. Evalúa si un producto tiene información válida e interpretable suficiente para sostener una experiencia de búsqueda antes de entrar en un índice. Un registro puede existir en un catálogo y aun así ser un mal candidato para recuperación.', question: '¿Este producto debería poder buscarse?' },
    system: { eyebrow: '04 / Sistema', title: 'Un camino visible del registro fuente al resultado.', body: 'Cada fase emite evidencia que conecta calidad de origen, decisiones de indexación y resultados de recuperación. El framework no trata la búsqueda como un problema aislado de interfaz.', steps: [['Catálogo fuente', 'Los registros ficticios conservan su estructura y sus restricciones.'], ['Mapear', 'Los campos pasan a un contrato de producto canónico.'], ['Validar', 'Se comprueban la evidencia requerida y la estructura.'], ['Normalizar', 'Reglas nombradas estandarizan valores interpretables.'], ['Evaluar', 'La preparación se evalúa según la información disponible.'], ['Elegibilidad', 'La admisión o rechazo conserva evidencia visible.'], ['Recuperar', 'Los productos elegibles se exploran con tres modos deterministas.'], ['Evaluar', 'Las consultas golden permiten comparar el comportamiento.']] },
    experience: { eyebrow: '05 / Experiencia de producto', title: 'Tres superficies, un argumento.', body: 'La experiencia pública convierte un flujo técnico en una historia de producto legible sin afirmar que el demostrador es infraestructura de producción.', surfaces: [['Landing', 'Explica el framework y el límite de demostración sintética.'], ['Demo de búsqueda', 'Explora productos ficticios con recuperación por keyword, semántica determinista e híbrida.'], ['Consola de preparación', 'Muestra escenarios de catálogo, validación, normalización, preparación, elegibilidad y admisión a indexación.']] },
    explainability: { eyebrow: '06 / Diseñar para explicar', title: 'Una decisión sirve más cuando su evidencia es visible.', body: 'SearchSignal evita correcciones ocultas y automatización opaca. Quien cuida el catálogo debe poder entender un cambio, bloqueo o admisión.', points: ['Las reglas de normalización nombradas muestran cómo cambió un valor.', 'Las decisiones de elegibilidad conservan la evidencia tras el estado.', 'El comportamiento determinista hace reproducible una misma entrada.', 'Los errores de proveedor y configuración siguen siendo controlados y legibles.'] },
    decisions: { eyebrow: '07 / Decisiones de producto', title: 'Las restricciones forman parte del producto.', items: [['Determinista por defecto', 'El comportamiento crítico de catálogo y elegibilidad es reproducible. El sistema es más acotado, pero deja un rastro más claro para inspeccionar y probar.'], ['Normalizar de forma explícita', 'El framework estandariza valores solo con reglas nombradas. No inventa hechos de producto en silencio.'], ['Separar demo y producción', 'Los fixtures sintéticos y proveedores deterministas no se presentan como infraestructura de comercio real.'], ['Fallar de forma cerrada', 'Sin configuración del proveedor de producción, el sistema responde con un fallo controlado. No vuelve al modo demo.'], ['Hacer visible la evidencia', 'Las decisiones de preparación y recuperación se pueden revisar, no solo aceptar.'], ['Mantener límites honestos', 'Conectores, proveedores, persistencia y operaciones futuras se documentan como trabajo futuro.']] },
    architecture: { eyebrow: '08 / Arquitectura', title: 'Responsabilidades claras hacen el sistema más entendible.', body: 'SearchSignal es un monorepo TypeScript con pnpm. Next.js y React forman la interfaz pública. Zod define estructuras compartidas. Vitest prueba el comportamiento. Vercel es el destino de despliegue. La arquitectura separa preocupaciones para que un cambio no oscurezca otro.', packages: [['Mapeo de origen', 'Traduce registros fuente a una estructura canónica.'], ['Validación y normalización', 'Comprueba evidencia requerida y aplica reglas explícitas.'], ['Preparación y elegibilidad', 'Evalúa si un registro puede sostener búsqueda.'], ['Recuperación y evaluación', 'Ejecuta modos deterministas y los compara con consultas golden.'], ['Interfaz pública', 'Explica el flujo mediante landing, demo y consola.']] },
    trust: { eyebrow: '09 / Confianza mediante límites', title: 'El demostrador especifica lo que existe.', implementedLabel: 'Implementado', futureLabel: 'Futuro', implemented: ['Catálogo ecommerce sintético', 'Recuperación determinista por keyword, semántica e híbrida', 'Validación y normalización de catálogo', 'Evaluación de preparación y elegibilidad', 'Evaluación con consultas golden', 'UI pública y verificación automatizada'], future: ['Integración real con Typesense', 'Proveedor real de embeddings', 'Conector de Shopify', 'Persistencia duradera de comercio', 'Analítica de búsqueda y sincronización en segundo plano', 'Infraestructura SaaS multi-tenant'] },
    quality: { eyebrow: '10 / Calidad y verificación', title: 'La evidencia también llega al build.', body: 'La verificación limpia registrada con Node 22 pasó instalación congelada, lint, comprobación de tipos, todos los tests, build de producción y el validador de preparación para Vercel. También cubre smoke de rutas, comprobaciones responsive y de teclado, además de fallos controlados. La evidencia de zoom real al 200% sigue documentada como pendiente.', checks: [['340', 'tests automatizados aprobados'], ['20', 'checks de preparación Vercel aprobados'], ['3', 'superficies públicas de producto'], ['0', 'afirmaciones sobre datos reales de comercios']] },
    outcome: { eyebrow: '11 / Resultado', title: 'Una forma de razonar sobre búsqueda antes del ranking.', body: 'SearchSignal es un demostrador funcional para una pregunta que suele quedar implícita: ¿está esta información de catálogo preparada para sostener búsqueda?', points: ['Un flujo inspeccionable de preparación de catálogo', 'Un sistema para explicar la elegibilidad de búsqueda', 'Un entorno controlado para comparar recuperación', 'Una prueba de concepto técnica con límites de producción documentados'] },
    next: { eyebrow: '12 / Siguiente paso', title: 'Pasos de validación lógicos, no un roadmap genérico.', items: ['Conectar un proveedor de búsqueda real.', 'Persistir evidencia de catálogo en el tiempo.', 'Añadir ingesta de Shopify.', 'Incorporar analítica de búsqueda con privacidad.', 'Ejecutar sincronización en segundo plano.', 'Probar el flujo con un comercio piloto.'] },
    final: { title: 'Una mejor búsqueda empieza con mejor información.', description: 'SearchSignal trata la calidad de búsqueda como un problema de sistemas antes de convertirlo en un problema de ranking.', live: 'Abrir demostrador', github: 'Ver repositorio en GitHub', back: 'Volver a casos de estudio' },
  },
}

function Section({ id, eyebrow, title, children, dark = false }: { id: string; eyebrow: string; title: string; children: React.ReactNode; dark?: boolean }) {
  return <section id={id} className={`searchsignal-section ui-section${dark ? ' searchsignal-section--dark' : ''}`} aria-labelledby={`${id}-heading`}><div className="searchsignal-container ui-section__container"><header className="searchsignal-heading ui-section-heading"><p className="ui-eyebrow">{eyebrow}</p><h2 id={`${id}-heading`}>{title}</h2></header>{children}</div></section>
}

function PipelineVisual({ steps }: { steps: Array<[string, string]> }) {
  return <ol className="searchsignal-pipeline" aria-label="SearchSignal product workflow">{steps.map(([name, description], index) => <li key={name}><span>{String(index + 1).padStart(2, '0')}</span><div><strong>{name}</strong><p>{description}</p></div></li>)}</ol>
}

function RecordVisual() {
  return <div className="searchsignal-record-visual" aria-label="Illustration of a product record becoming eligible for search"><div className="searchsignal-record searchsignal-record--source"><span>Source record</span><p><b>sku</b> WDN-04?</p><p><b>price</b> $1,299</p><p><b>availability</b> maybe</p><p><b>material</b> walnut / wood</p></div><span className="searchsignal-record-arrow" aria-hidden="true">→</span><div className="searchsignal-record searchsignal-record--ready"><span>Canonical record</span><p><b>externalId</b> WDN-04</p><p><b>price</b> 129900 USD</p><p><b>availability</b> in_stock</p><p><b>material</b> walnut</p><em>Eligible for search</em></div></div>
}

function ProductVisual() {
  return <div className="searchsignal-product-visual" aria-label="Illustration of SearchSignal product surfaces"><div className="searchsignal-browser-bar"><i></i><i></i><i></i><span>searchsignal / demo</span></div><div className="searchsignal-product-visual__body"><aside><span>SearchSignal</span><b>Landing</b><b>Search demo</b><b>Readiness console</b></aside><div className="searchsignal-product-visual__workspace"><div className="searchsignal-searchbar">walnut desk <span>Search</span></div><div className="searchsignal-mode-row"><b>Keyword</b><b>Semantic</b><b>Hybrid</b></div><div className="searchsignal-result"><span>01</span><div><strong>Walnut writing desk</strong><p>In stock · $1,299.00 · Walnut</p></div><em>eligible</em></div><div className="searchsignal-console-row"><span>Readiness</span><strong>Pass</strong><span>Normalization</span><strong>4 rules</strong></div></div></div></div>
}

export default function SearchSignalPage() {
  const pathname = usePathname()
  const locale = getLocaleFromPath(pathname)
  const content = copy[locale]

  return <><Header locale={locale} /><main id="main-content" className="searchsignal-case-study"><section className="searchsignal-hero" aria-labelledby="searchsignal-title"><div className="searchsignal-container ui-section__container"><Link href={localizePath('/case-studies', locale)} className="searchsignal-back">← {content.back}</Link><div className="searchsignal-hero__grid"><div><p className="ui-eyebrow">{content.eyebrow}</p><h1 id="searchsignal-title">Search<span>Signal</span></h1><p className="searchsignal-hero__subtitle">{content.subtitle}</p><p className="searchsignal-hero__description">{content.description}</p><p className="searchsignal-status"><i></i>{content.status}</p><div className="searchsignal-actions" aria-label={content.linksLabel}><a href={liveUrl} target="_blank" rel="noreferrer" className="ui-button">{content.live} <span aria-hidden="true">↗</span></a><a href={githubUrl} target="_blank" rel="noreferrer" className="searchsignal-actions__secondary">{content.github} <span aria-hidden="true">↗</span></a></div></div><ProductVisual /></div><dl className="searchsignal-meta">{content.metadata.map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></div></section><CaseStudyMiniNav ariaLabel="SearchSignal case study sections" items={content.nav} />

  <Section id="premise" {...content.premise} dark><div className="searchsignal-premise"><p>{content.premise.body}</p><RecordVisual /></div></Section>
  <Section id="problem" {...content.problem}><div className="searchsignal-prose"><p>{content.problem.body}</p></div><div className="searchsignal-card-grid searchsignal-card-grid--three">{content.problem.cards.map(([title, description], index) => <article key={title}><span>{String(index + 1).padStart(2, '0')}</span><h3>{title}</h3><p>{description}</p></article>)}</div></Section>
  <Section id="insight" {...content.insight} dark><div className="searchsignal-insight"><p>{content.insight.body}</p><blockquote>{content.insight.question}</blockquote></div></Section>
  <Section id="system" {...content.system}><div className="searchsignal-prose"><p>{content.system.body}</p></div><PipelineVisual steps={content.system.steps} /></Section>
  <Section id="experience" {...content.experience} dark><div className="searchsignal-prose searchsignal-prose--inverse"><p>{content.experience.body}</p></div><div className="searchsignal-experience-grid">{content.experience.surfaces.map(([title, description], index) => <article key={title}><span>{String(index + 1).padStart(2, '0')}</span><h3>{title}</h3><p>{description}</p></article>)}</div></Section>
  <Section id="explainability" {...content.explainability}><div className="searchsignal-explainability"><div className="searchsignal-prose"><p>{content.explainability.body}</p></div><ul>{content.explainability.points.map(point => <li key={point}>{point}</li>)}</ul></div></Section>
  <Section id="decisions" {...content.decisions} dark><div className="searchsignal-card-grid searchsignal-card-grid--decisions">{content.decisions.items.map(([title, description], index) => <article key={title}><span>{String(index + 1).padStart(2, '0')}</span><h3>{title}</h3><p>{description}</p></article>)}</div></Section>
  <Section id="architecture" {...content.architecture}><div className="searchsignal-prose"><p>{content.architecture.body}</p></div><div className="searchsignal-architecture">{content.architecture.packages.map(([title, description], index) => <article key={title}><span>{String(index + 1).padStart(2, '0')}</span><div><h3>{title}</h3><p>{description}</p></div></article>)}</div></Section>
  <Section id="boundaries" {...content.trust} dark><div className="searchsignal-boundary-grid"><article><p>{content.trust.implementedLabel}</p><ul>{content.trust.implemented.map(item => <li key={item}>{item}</li>)}</ul></article><article><p>{content.trust.futureLabel}</p><ul>{content.trust.future.map(item => <li key={item}>{item}</li>)}</ul></article></div></Section>
  <Section id="quality" {...content.quality}><div className="searchsignal-prose"><p>{content.quality.body}</p></div><div className="searchsignal-quality-grid">{content.quality.checks.map(([value, label]) => <article key={label}><strong>{value}</strong><span>{label}</span></article>)}</div></Section>
  <Section id="outcome" {...content.outcome} dark><div className="searchsignal-prose searchsignal-prose--inverse"><p>{content.outcome.body}</p></div><ul className="searchsignal-outcome-list">{content.outcome.points.map(point => <li key={point}>{point}</li>)}</ul></Section>
  <Section id="next" {...content.next}><ol className="searchsignal-next-list">{content.next.items.map((item, index) => <li key={item}><span>{String(index + 1).padStart(2, '0')}</span>{item}</li>)}</ol></Section>
  <section className="searchsignal-final ui-section" aria-labelledby="searchsignal-final-heading"><div className="searchsignal-container ui-section__container"><p className="ui-eyebrow">SearchSignal</p><h2 id="searchsignal-final-heading">{content.final.title}</h2><p>{content.final.description}</p><div className="searchsignal-actions"><a href={liveUrl} target="_blank" rel="noreferrer" className="ui-button">{content.final.live} <span aria-hidden="true">↗</span></a><a href={githubUrl} target="_blank" rel="noreferrer" className="searchsignal-actions__secondary">{content.final.github} <span aria-hidden="true">↗</span></a><Link href={localizePath('/case-studies', locale)} className="searchsignal-actions__secondary">{content.final.back} →</Link></div></div></section></main><CaseStudyNext currentHref="/case-studies/searchsignal" locale={locale} accentColor="var(--color-0)" /><Footer locale={locale} /></>
}
